// <auto-generated />
using System;
using System.Collections.Generic;
using BudgetCouple.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetCouple.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414204634_AddContaPagamentoIdToCartao")]
    partial class AddContaPagamentoIdToCartao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Cartoes.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bandeira");

                    b.Property<Guid>("ContaPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_pagamento_id");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_fechamento");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<string>("Icone")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icone");

                    b.Property<decimal>("Limite")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("cartoes", (string)null);
                });

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Icone")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<bool>("Sistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sistema");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5444),
                            Cor = "#DC2626",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5443),
                            Icone = "home",
                            Nome = "Moradia",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5452),
                            Cor = "#F97316",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5452),
                            Icone = "utensils",
                            Nome = "Alimentação",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5459),
                            Cor = "#EAB308",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5459),
                            Icone = "car",
                            Nome = "Transporte",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5465),
                            Cor = "#EC4899",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5465),
                            Icone = "heart-pulse",
                            Nome = "Saúde",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5472),
                            Cor = "#3B82F6",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5471),
                            Icone = "graduation-cap",
                            Nome = "Educação",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440006"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5478),
                            Cor = "#8B5CF6",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5478),
                            Icone = "film",
                            Nome = "Lazer",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440007"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5485),
                            Cor = "#06B6D4",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5484),
                            Icone = "repeat",
                            Nome = "Assinaturas",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440008"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5491),
                            Cor = "#D946EF",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5491),
                            Icone = "shirt",
                            Nome = "Vestuário",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440009"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5497),
                            Cor = "#14B8A6",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5497),
                            Icone = "paw-print",
                            Nome = "Pets",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000a"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5505),
                            Cor = "#F43F5E",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5505),
                            Icone = "gift",
                            Nome = "Presentes",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000b"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5511),
                            Cor = "#64748B",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5511),
                            Icone = "receipt",
                            Nome = "Impostos e Taxas",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000c"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5517),
                            Cor = "#6366F1",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5517),
                            Icone = "landmark",
                            Nome = "Serviços Financeiros",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000d"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5523),
                            Cor = "#78716C",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5523),
                            Icone = "more-horizontal",
                            Nome = "Outros",
                            Sistema = false,
                            Tipo = "DESPESA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000e"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5529),
                            Cor = "#10B981",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5529),
                            Icone = "wallet",
                            Nome = "Salário",
                            Sistema = false,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000f"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5535),
                            Cor = "#84CC16",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5535),
                            Icone = "award",
                            Nome = "Bonificação",
                            Sistema = false,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440010"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5541),
                            Cor = "#06B6D4",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5541),
                            Icone = "trending-up",
                            Nome = "Rendimentos",
                            Sistema = false,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440011"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5547),
                            Cor = "#8B5CF6",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5547),
                            Icone = "briefcase",
                            Nome = "Freelance",
                            Sistema = false,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440012"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5553),
                            Cor = "#14B8A6",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5553),
                            Icone = "undo-2",
                            Nome = "Reembolso",
                            Sistema = false,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440013"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5559),
                            Cor = "#78716C",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5559),
                            Icone = "more-horizontal",
                            Nome = "Outros",
                            Sistema = false,
                            Tipo = "RECEITA"
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440014"),
                            Ativa = true,
                            AtualizadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5565),
                            Cor = "#0891B2",
                            CriadoEm = new DateTime(2026, 4, 14, 20, 46, 33, 989, DateTimeKind.Utc).AddTicks(5565),
                            Icone = "credit-card",
                            Nome = "Pagamento de Fatura de Cartão",
                            Sistema = true,
                            Tipo = "DESPESA"
                        });
                });

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Contas.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Icone")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Lancamentos.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<string>>("Anexos")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new List<string>())
                        .HasColumnName("anexos");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("classificacao");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsParcelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_parcelada");

                    b.Property<bool>("IsRecorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recorrente");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("natureza");

                    b.Property<Guid?>("RecorrenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorrencia_id");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("status_pagamento");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategoria_id");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new List<string>())
                        .HasColumnName("tags");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_lanc_data");

                    b.HasIndex("CartaoId", "Data")
                        .HasDatabaseName("ix_lanc_cartao_data");

                    b.HasIndex("CategoriaId", "Data")
                        .HasDatabaseName("ix_lanc_cat_data");

                    b.HasIndex("ContaId", "Data")
                        .HasDatabaseName("ix_lanc_conta_data");

                    b.ToTable("lancamentos", null, t =>
                        {
                            t.HasCheckConstraint("chk_origem", "(conta_id IS NOT NULL AND cartao_id IS NULL) OR (conta_id IS NULL AND cartao_id IS NOT NULL) OR (conta_id IS NULL AND cartao_id IS NULL AND natureza = 'PREVISTA')");
                        });
                });

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Recorrencias.Recorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("frequencia");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_json");

                    b.HasKey("Id");

                    b.ToTable("recorrencias", (string)null);
                });

            modelBuilder.Entity("BudgetCouple.Domain.Budgeting.Metas.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataLimite")
                        .HasColumnType("date")
                        .HasColumnName("data_limite");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("PercentualAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(80)
                        .HasColumnName("percentual_alerta");

                    b.Property<string>("Periodo")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("periodo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_alvo");

                    b.Property<decimal>("ValorAtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_atual");

                    b.HasKey("Id");

                    b.ToTable("metas", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Meta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BudgetCouple.Domain.Identity.AppConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailNotificacao")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_notificacao");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTime?>("PinSetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_set_at");

                    b.Property<List<string>>("TelegramChatIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new List<string>())
                        .HasColumnName("telegram_chat_ids");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("light")
                        .HasColumnName("tema");

                    b.HasKey("Id");

                    b.ToTable("app_config", (string)null);
                });

            modelBuilder.Entity("BudgetCouple.Domain.Imports.RegraClassificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Padrao")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("padrao");

                    b.Property<int>("Prioridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("prioridade");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategoria_id");

                    b.Property<string>("TipoPadrao")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo_padrao");

                    b.HasKey("Id");

                    b.ToTable("regras_classificacao", (string)null);
                });

            modelBuilder.Entity("BudgetCouple.Domain.Budgeting.Metas.MetaEconomia", b =>
                {
                    b.HasBaseType("BudgetCouple.Domain.Budgeting.Metas.Meta");

                    b.HasDiscriminator().HasValue("ECONOMIA");
                });

            modelBuilder.Entity("BudgetCouple.Domain.Budgeting.Metas.MetaReducaoCategoria", b =>
                {
                    b.HasBaseType("BudgetCouple.Domain.Budgeting.Metas.Meta");

                    b.HasDiscriminator().HasValue("REDUCAO_CATEGORIA");
                });

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Categorias.Categoria", b =>
                {
                    b.OwnsMany("BudgetCouple.Domain.Accounting.Categorias.Subcategoria", "Subcategorias", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Ativa")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("ativa");

                            b1.Property<DateTime>("AtualizadoEm")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizado_em");

                            b1.Property<Guid>("CategoriaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CriadoEm")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criado_em");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("nome");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoriaId");

                            b1.ToTable("subcategorias", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("BudgetCouple.Domain.Accounting.Lancamentos.Lancamento", b =>
                {
                    b.OwnsOne("BudgetCouple.Domain.Accounting.Lancamentos.ValueObjects.DadosParcelamento", "DadosParcelamento", b1 =>
                        {
                            b1.Property<Guid>("LancamentoId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("LancamentoPaiId")
                                .HasColumnType("uuid")
                                .HasColumnName("lancamento_pai_id");

                            b1.Property<int>("ParcelaAtual")
                                .HasColumnType("integer")
                                .HasColumnName("parcela_atual");

                            b1.Property<int>("TotalParcelas")
                                .HasColumnType("integer")
                                .HasColumnName("total_parcelas");

                            b1.HasKey("LancamentoId");

                            b1.ToTable("lancamentos");

                            b1.WithOwner()
                                .HasForeignKey("LancamentoId");
                        });

                    b.Navigation("DadosParcelamento");
                });
#pragma warning restore 612, 618
        }
    }
}
